name: Pull Request CI

on:
  pull_request:
    branches: ['master']

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start lint checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run lint:check
  types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start types checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run types
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start spell checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run spell
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start spell checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run format:check
  version-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start spell checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm install
      - run: npm run version:check
  merge:
    needs:
      - format
      - lint
      - spell
      - types
      - version-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start spell checking
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: echo 'merging is available'
    timeout-minutes: 5
